This notebook is used for the Coursera Capstone Project.

In [2]:
import pandas as pd
import numpy as np

In [3]:
print("Hello Capstone Project Course!")

Hello Capstone Project Course!


In [4]:
path = "https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv"
df = pd.read_csv(path)
df.columns

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Index(['SEVERITYCODE', 'X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO',
       'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
       'EXCEPTRSNDESC', 'SEVERITYCODE.1', 'SEVERITYDESC', 'COLLISIONTYPE',
       'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE',
       'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE', 'SDOT_COLDESC',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SDOTCOLNUM', 'SPEEDING', 'ST_COLCODE', 'ST_COLDESC',
       'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR'],
      dtype='object')

In [5]:
df["SEVERITYCODE"].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

In [6]:
from sklearn.utils import resample

In [7]:
# Downsampling

df_major = df[df.SEVERITYCODE == 1]
df_minor = df[df.SEVERITYCODE == 2]

df_sample = resample(df_major,
                    replace = False,
                    n_samples = 58188,
                    random_state = 123)

new_df = pd.concat([df_sample, df_minor])
new_df.SEVERITYCODE.value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [8]:
for col in ['WEATHER', 'ROADCOND', 'LIGHTCOND', 'SEVERITYCODE']:
    new_df[col] = new_df[col].astype('category')
new_df.dtypes

SEVERITYCODE      category
X                  float64
Y                  float64
OBJECTID             int64
INCKEY               int64
COLDETKEY            int64
REPORTNO            object
STATUS              object
ADDRTYPE            object
INTKEY             float64
LOCATION            object
EXCEPTRSNCODE       object
EXCEPTRSNDESC       object
SEVERITYCODE.1       int64
SEVERITYDESC        object
COLLISIONTYPE       object
PERSONCOUNT          int64
PEDCOUNT             int64
PEDCYLCOUNT          int64
VEHCOUNT             int64
INCDATE             object
INCDTTM             object
JUNCTIONTYPE        object
SDOT_COLCODE         int64
SDOT_COLDESC        object
INATTENTIONIND      object
UNDERINFL           object
WEATHER           category
ROADCOND          category
LIGHTCOND         category
PEDROWNOTGRNT       object
SDOTCOLNUM         float64
SPEEDING            object
ST_COLCODE          object
ST_COLDESC          object
SEGLANEKEY           int64
CROSSWALKKEY         int64
H

In [9]:
new_df["WEATHER"].value_counts()

Clear                       67946
Raining                     20584
Overcast                    16834
Unknown                      6851
Snowing                       474
Other                         406
Fog/Smog/Smoke                355
Sleet/Hail/Freezing Rain       63
Blowing Sand/Dirt              30
Severe Crosswind               13
Partly Cloudy                   4
Name: WEATHER, dtype: int64

In [10]:
new_df["ROADCOND"].value_counts()

Dry               76000
Wet               29374
Unknown            6806
Ice                 678
Snow/Slush          528
Other                83
Standing Water       57
Sand/Mud/Dirt        47
Oil                  39
Name: ROADCOND, dtype: int64

In [11]:
new_df["LIGHTCOND"].value_counts()

Daylight                    71503
Dark - Street Lights On     29133
Unknown                      6062
Dusk                         3592
Dawn                         1535
Dark - No Street Lights       866
Dark - Street Lights Off      703
Other                         127
Dark - Unknown Lighting         7
Name: LIGHTCOND, dtype: int64

In [12]:
new_df["SEVERITYCODE"].value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [13]:
new_df["WEATHER"] = new_df["WEATHER"].cat.codes
new_df["ROADCOND"] = new_df["ROADCOND"].cat.codes
new_df["LIGHTCOND"] = new_df["LIGHTCOND"].cat.codes
x = np.asarray(new_df[['WEATHER','ROADCOND','LIGHTCOND']])
x[0:5]

array([[ 6,  8,  2],
       [ 1,  0,  5],
       [10,  7,  8],
       [ 1,  0,  5],
       [ 1,  0,  5]], dtype=int8)

In [14]:
y = np.asarray(new_df['SEVERITYCODE'])
y[0:5]

array([1, 1, 1, 1, 1])

In [15]:
from sklearn import preprocessing
x = preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.15236718,  1.52797946, -1.21648407],
       [-0.67488   , -0.67084969,  0.42978835],
       [ 2.61416492,  1.25312582,  2.07606076],
       [-0.67488   , -0.67084969,  0.42978835],
       [-0.67488   , -0.67084969,  0.42978835]])

In [16]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)
print('Train set: ', x_train.shape, y_train.shape)
print('Test set: ', x_test.shape, y_test.shape)

Train set:  (81463, 3) (81463,)
Test set:  (34913, 3) (34913,)


In [31]:
#KNN

from sklearn.neighbors import KNeighborsClassifier
k = 17

In [32]:
NB = KNeighborsClassifier(n_neighbors = k).fit(x_train, y_train)
NB

kyhat = NB.predict(x_test)
kyhat[0:5]

array([1, 1, 1, 1, 1])

In [78]:
jaccard_similarity_score(y_test, kyhat)

0.5190616675736831

In [81]:
from sklearn.metrics import f1_score
f1_score(y_test, kyhat, average='macro')

0.5097879480067022

In [53]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion="entropy", max_depth = 7)
dt.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [85]:
dt_y_pred = dt.predict(x_test)

In [97]:
jaccard_similarity_score(y_test, dt_y_pred)

0.5626843869045914

In [98]:
f1_score(y_test, dt_y_pred, average='macro')

0.5385207275454998

In [86]:
# Log Regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [87]:
LR = LogisticRegression(C=6, solver='liblinear').fit(x_train,y_train)

In [90]:
from sklearn.metrics import log_loss
LR_y_pred = LR.predict(x_test)
LR_y_prob = LR.predict_proba(x_test)
log_loss(y_test, LR_y_prob)

0.6855328681086409

In [91]:
jaccard_similarity_score(y_test, LR_y_pred)

0.523501274596855

In [92]:
f1_score(y_test, LR_y_pred, average='macro')

0.5098573271706865